---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUJwSwPfVpUyBA6JXaj3JNsDkpsNQwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTAxMjA1NDAwWhcNMjQxMDMwMjA1NDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ANu+VWn3s+903FQBZ13Q2RKP3FUqupWH/eiJrVLlbMCa9rxKEwZUfSnrtIQ18Nfy
    Q4OGKtQdUDvMDjG41TPbQ51lglbAFq7s02FxKGz7yafbQyAk35SmRwt7QYq6/dfp
    Jk7FrQrEy31QxRBsvN0lakHo9EtPFjCQC+VEp+x86OiO+FeQyHoINAfdvYrcaSS9
    rdkDt2cWag17KiLpQT601oRe9m9YvjagL39HepViT4q/bpTGs64pJCIW0+XP0ORt
    uNFXV9iNC/gMhoCtM6iZfb5UxRtfpv6yX1Lrv4oqYyGDLhxqMfL6LvTRjRrTpfBT
    M6xh5E0tazJx61eYSTukI9j2n0407tV4Lcd5KcBBLDmuGsOZfr0OiJgFOlCJIeXc
    3RKc/vv9GyEzTt/8gqfAhfFgaTKs8XhBm/dscJJl6Jb2gLfKE7u0KFU5mI+M+lyt
    Ms0Je8a+bsTpzo8rwNjOsvNDTvlN/x7Fw5/hPaRHz7+IEbOT8q+N0ilrMrH/p9+8
    bI6GjyJjaHrTJRBsWVhPd57rah9VZ14/hsf+s4HMzWBLTNOusgVKotYnGJkBNeJk
    QobJeTPyq4Re5BAM1jrUdVA5KB407Dk6qksYZkGFulivTo5bF+vfZqyhskquJWOW
    uEZecdVsrMbXhKu2mHV1o/v4jPuWMqCzu4qbZTUL3P0xAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRkdCCuHZZeCGW8
    /DCc3OU1w1GsizANBgkqhkiG9w0BAQ0FAAOCAgEAotwDayj+CIbwAhPa7vaLYhDD
    A07uNtvNZ/5Mpm6d5rWlkKPBhiNrj9XoAHD0JHyTLJ95yCDjHdpxWflZQeZFDA5s
    crmZ3YzqaAPLqCr1SXTqO+COSqxYSsgP+F9/21CboY5hhXc9ckSVjkWYPiICtmjr
    rgl1tKrF/4g8FVUMXdc/HmOPOAKYdsWwAl7DSrmDfP8ZXeTPY84Bunmr/Tr38Dej
    WY5N7JTdiOyjp8vv4oeU9LBk3LqgNCPJ9IHWkdtLCWidD0MGBR2cwv1AOx3/fk7t
    hU0Ey9DJY7uye0mGRyTxjb7CVkaHoFJkn015G8YNwN0M6pD8qrGXXXryQ58vxD5J
    JuCq8nbP/9lZOlercDxO/wfl5D0NyeoPkWpVPnaNwJywjaZJkglK1QdKA2BT3ce2
    nmoIC+dOqoa5fuRV5Q/oV+3J6T71dPVJsUvUGvAY0eDJ/OoSrNmdRc2vvVKMA0nf
    px2P9tW2YfLk6Mv7c/d4YR2IGgASec9gzRKLisuCGygq+XaeY/yc3YNtFE551Gf7
    A19Mdf5RmEvjQoZZjp2Ot+tTXxSyP/mZ8qFv19dVhNzci/XFQDJpBHrp/bNJJdmj
    FLNNo8hIANSmLJgfWcm/zuDM8jno03gDkNR6fE4zurFlzE6xiNEpQjCW8ZO2k+UC
    e/XMDYljKnMV+xT672E=
    -----END CERTIFICATE-----
    
